### ISSUE TITLE
Installs php 5.5.9-1ubuntu4.7 (cli)

### ISSUE THREAD

**Issue by HeathNaylor** [opscode-cookbooks/php#118]
The README says that PHP 5.3 will be installed, but I am getting 5.5.9. Is this a bug or do we need to update the changelog and readme? If I use a Ubuntu 12.04 box I get 5.3, but on Ubuntu 14.04 I get 5.5.9.

**Comment by Rockstar04** [comment]
The readme information is outdated, even when installing from source 5.5 is the default version now. https://github.com/opscode-cookbooks/php/blob/master/attributes/default.rb#L82-L84

**Comment by tas50** [comment]
I've removed the reference to PHP 5.3 in the readme here https://github.com/opscode-cookbooks/php/commit/c15a7bf0550492f4012acdefcc20fdfb793cd986 since that was no longer accurate.
