### ISSUE TITLE
Fails on FreeBSD

### ISSUE THREAD

**Issue by awartner** [opscode-cookbooks/php#120]
Various attributes and resources fail on FreeBSD due to path, user and package name mismatches.

**Comment by bheuvel** [comment]
Would be nice if the referenced PR ( #119 ) would be aproved.

I'm also working on getting FreeBSD back in with Apache2 ( PR: https://github.com/svanzoest-cookbooks/apache2/pull/358 ) 
And eventually these will help making the Nagios cookbook work again, with my staged changes ( https://github.com/bheuvel/nagios/tree/freebsd_fulltest )

**Comment by bheuvel** [comment]
PR for Apache has been merged; FreeBSD 10.1 is back in for Apache.

If the PR for PHP can be merged ( #119 ), then the Nagios cookbook will get FreeBSD support as well.
