### ISSUE TITLE
Deprecated configuration items in the php.ini template

### ISSUE THREAD

**Issue by stissot** [opscode-cookbooks/php#121]
It's recommended that these settings be removed as they will be removed from future PHP versions
-> session.bug_compat_42
-> session.bug_compat_warn
-> register_globals
-> magic_quotes_gpc
-> magic_quotes_runtime
-> safe_mode
-> register_long_arrays

**Comment by Rockstar04** [comment]
As far as I know having them wont cause any issues when the installed version of PHP does not support them, and since we still support 12.04 which has PHP 5.3, most are technically valid.
