### ISSUE TITLE
Chefspec matchers don't exists

### ISSUE THREAD

**Issue by yoshiwaan** [opscode-cookbooks/php#129]
matchers for php_pear and php_pear_channel don't exist in the cookbook

**Comment by yoshiwaan** [comment]
PR https://github.com/opscode-cookbooks/php/pull/128 contains library.

**Comment by yoshiwaan** [comment]
This was merged

**Comment by Rockstar04** [comment]
Ah thanks for cleaning this up @yoshiwaan
