### ISSUE TITLE
Chef Client 13.0 Support

### ISSUE THREAD

**Issue by Rockstar04** [opscode-cookbooks/php#134]
When using Chef Client 12.4 deprication notices are given for our LWRPs.

We may need to restructure the current LWRPs if the rewrite is not completed before chef 13 is out.

**Comment by tas50** [comment]
@Rockstar04 Do you have a list of the deprecation notices that are being thrown?

**Comment by Rockstar04** [comment]
I took a look at the kitchen runs for this cookbook itself and some internal wrapper cookbooks I had written and I dont seem them anymore, so I will assume it was a dependency cookbook that has since been updated.
