### ISSUE TITLE
ext_conf_dir should be /etc/php5/mods-available for PHP5.4

### ISSUE THREAD

**Issue by HuffAndPuff** [opscode-cookbooks/php#76]
As the title says, the attribute ext_conf_dir should be `/etc/php5/mods-available` when installing PHP version 5.4 or above on Debian or Ubuntu.

I'd do a pull request but I'm not sure how to detect what PHP version is being installed from a package.

http://www.lornajane.net/posts/2012/managing-php-5-4-extensions-on-ubuntu

**Comment by Rockstar04** [comment]
Fixed in PR #107
