### ISSUE TITLE
Cookbook version attribute overrides ohai attribute

### ISSUE THREAD

**Issue by marpada** [opscode-cookbooks/php#77]
Ohai provides a ['php']['version'] attribute that returns the installed php version (by parsing the output of php -v).

The php cookbook  sets a default value for that attribute ('5.5.9') so it cannot longer be used to determine the actual php version, as least when using the install from package method.

**Comment by Rockstar04** [comment]
Making a change to correct this issue would be a backwards compatibility breaking change. 

With that said, this will have to wait to be fixed as part of Someara's total rewrite

**Comment by Rockstar04** [comment]
I'm labeling this as a BC break and closing the issue. Before we release 2.0 we will check all BC issues and make sure they are taken care of.
