### ISSUE TITLE
Problem with php_pear on Ubuntu?

### ISSUE THREAD

**Issue by cajund** [opscode-cookbooks/php#78]
Hi Folks,

A call like this:

```
php_pear "odbc" do
    action :install
end
```

Results in an error:

```
RuntimeError
------------
Package obdc not found in either PEAR or PECL.
```

But switching this to package seems to work:

```
package php5-odbc do
    action :install
end
```

This is on a Virtualbox Precise64 box (Ubuntu). I have seen some indications that this may be related to Ubuntu. Is there a different in such an environment?

Thanks.

**Comment by Rockstar04** [comment]
It actually looks like the package name is PDO_odbc in pecl. Trying to install just odbc from the command line fails with your error, but using the full extention name runs a successful installation
