### ISSUE TITLE
error_reporting directive should not use quotes

### ISSUE THREAD

**Issue by moleculezz** [opscode-cookbooks/php#88]
Hi,

I have come across an issue when trying to modify the `error_reporting` directive.
Because the value is in quotes it cannot read it properly.
Doing `php -i` returns `error_reporting => no value => no value`
While doing the same when it's not between quotes returns `error_reporting => 22527 => 22527`

**Comment by sschueller** [comment]
Yes, please fix this. 

On Debian it does not work properly. Quotes need to go. For things like timezone they need to be specified manually.

**Comment by Rockstar04** [comment]
#89 has been merged and closed
