### ISSUE TITLE
could not find recipe php5 for cookbook php

### ISSUE THREAD

**Issue by pullareddy009** [opscode-cookbooks/php#90]
Hello .

While running sugarcrm cookbook book getting below error 

 ================================================================================
 Recipe Compile Error
================================================================================
 Chef::Exceptions::RecipeNotFound
 --------------------------------
could not find recipe php5 for cookbook php

**Comment by Rockstar04** [comment]
I'm going to close this issue.

If anyone has anymore information, we can re-open it.
